# codemagic.yaml

# Define the name and environment for your workflow.
workflows:
  ionic-capacitor-android-workflow:
    name: Ionic Capacitor Android Debug Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - |
        # Ensure the Gradlew script is executable
        cd android
        chmod +x ./gradlew  # Add this line to make gradlew executable
        ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
