# codemagic.yaml

# Define the name and environment for your workflow.
workflows:
  ionic-capacitor-android-workflow:
    name: Ionic Capacitor Android Debug Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.printer"
      node: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install

      - name: Build Ionic project
        script: |
          npm run build

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Sync with Capacitor
        script: |
          npx cap sync android
      - name: Build Android debug
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
