# codemagic.yaml

# Define the name and environment for your workflow.
workflows:
  ionic-capacitor-android-workflow:
    name: Ionic Capacitor Android Debug Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
        node: latest
    scripts:
            - npm install
            - npx cap sync
            - |
                # build Android
                cd android
                ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
